### ISSUE TITLE
Not sure about keeping the .vscode folder

### ISSUE THREAD

**Issue by ChrisVilches** [ChrisVilches/Algorithms#8]
I need the formatting specifications to be shared though.

**Comment by Uriyah3** [comment]
It's fine to share files from that folder as long as absolue paths aren't used in those files. More information here: https://stackoverflow.com/a/57749909

**Comment by ChrisVilches** [comment]
@Uriyah3 

F
https://github.com/ChrisVilches/Algorithms/blob/main/.vscode/c_cpp_properties.json#L8

**Comment by ChrisVilches** [comment]
Ok I don't care too much about this.
